create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null default 0,
  cost numeric not null default 0,
  unit text not null default 'pcs',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  name text not null,
  qty_multiplier numeric not null default 1,
  price numeric not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists stock_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  batch_code text not null,
  purchase_date date not null,
  qty_initial numeric not null default 0,
  qty_remaining numeric not null default 0,
  cost numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  transaction_date timestamptz not null default now(),
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  cash_received numeric not null default 0,
  change_amount numeric not null default 0,
  payment_method text not null default 'Cash',
  profit numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references transactions(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  variant_id bigint references product_variants(id) on delete set null,
  name text not null,
  product_name text,
  variant_name text,
  category text,
  unit text,
  qty numeric not null default 0,
  qty_multiplier numeric not null default 1,
  fifo_qty numeric not null default 0,
  price numeric not null default 0,
  subtotal numeric not null default 0,
  total_cost numeric not null default 0,
  profit numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists transaction_item_batches (
  id bigint generated by default as identity primary key,
  transaction_item_id bigint not null references transaction_items(id) on delete cascade,
  stock_batch_id bigint references stock_batches(id) on delete set null,
  batch_code text not null,
  purchase_date date,
  qty numeric not null default 0,
  cost numeric not null default 0,
  total_cost numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists store_settings (
  id bigint primary key default 1,
  store_name text not null default 'Toko Telon Mindi',
  address text not null default '',
  phone text not null default '',
  receipt_note text not null default 'Terima kasih sudah belanja.',
  low_stock_threshold numeric not null default 10,
  updated_at timestamptz not null default now(),
  constraint single_settings_row check (id = 1)
);

create index if not exists idx_product_variants_product_id
on product_variants(product_id);

create index if not exists idx_stock_batches_product_id
on stock_batches(product_id);

create index if not exists idx_stock_batches_purchase_date
on stock_batches(purchase_date);

create index if not exists idx_transactions_transaction_date
on transactions(transaction_date);

create index if not exists idx_transaction_items_transaction_id
on transaction_items(transaction_id);

create index if not exists idx_transaction_item_batches_item_id
on transaction_item_batches(transaction_item_id);

insert into store_settings (
  id,
  store_name,
  address,
  phone,
  receipt_note,
  low_stock_threshold
)
values (
  1,
  'Toko Telon Mindi',
  '',
  '',
  'Terima kasih sudah belanja.',
  10
)
on conflict (id) do nothing;