export const dummyProducts = [
  {
    id: 1,
    name: "Sosis Champ 375gr",
    category: "Sosis",
    price: 24500,
    cost: 20500,
    stock: 20,
    unit: "pack",
    active: true,
  },
  {
    id: 2,
    name: "Sosis Kanzler Singles",
    category: "Sosis",
    price: 10500,
    cost: 8500,
    stock: 35,
    unit: "pcs",
    active: true,
  },
  {
    id: 3,
    name: "Nugget Fiesta 500gr",
    category: "Nugget",
    price: 48500,
    cost: 42000,
    stock: 14,
    unit: "pack",
    active: true,
  },
  {
    id: 4,
    name: "Nugget So Good 400gr",
    category: "Nugget",
    price: 39500,
    cost: 33000,
    stock: 18,
    unit: "pack",
    active: true,
  },
  {
    id: 5,
    name: "Bakso Sapi Warisan",
    category: "Bakso",
    price: 32500,
    cost: 27000,
    stock: 16,
    unit: "pack",
    active: true,
  },
  {
    id: 6,
    name: "Kulit Pangsit 8cm",
    category: "Kulit Pangsit",
    price: 3000,
    cost: 2200,
    stock: 80,
    unit: "pcs",
    active: true,
  },
  {
    id: 8,
    name: "Es Kristal 5kg",
    category: "Es Kristal",
    price: 8000,
    cost: 5000,
    stock: 50,
    unit: "pack",
    active: true,
  },
  {
    id: 9,
    name: "Es Wawan",
    category: "Es Wawan",
    price: 1000,
    cost: 700,
    stock: 120,
    unit: "pcs",
    active: true,
  },
];